### ISSUE TITLE
Feature: Allow custom Ollama IP

### ISSUE THREAD

**Issue by imSp4rky** [voytas75/AIPSTeam#2]
https://github.com/voytas75/AIPSTeam/blob/da018f4c6a26b1b1c41a3d7359a302df734c8ab5/AIPSTeam.ps1#L2163

Some configurations setup Windows Environment to have the IP of the machine. we check the windows system environment for OLLAMA_HOST and use that IP instead of the localhost one.

Example below of the configuration
https://github.com/ollama/ollama/blob/main/docs/faq.md#setting-environment-variables-on-windows

**Comment by voytas75** [comment]
Sure 👍
